/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {},
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        light: {
          'color-scheme': 'light',
          primary: '#185FA5',
          'primary-content': '#ffffff',
          secondary: '#378ADD',
          'secondary-content': '#ffffff',
          accent: '#1D9E75',
          'accent-content': '#ffffff',
          neutral: '#2C3E50',
          'neutral-content': '#ffffff',
          'base-100': '#ffffff',
          'base-200': '#F2F5F9',
          'base-300': '#E2E8F0',
          'base-content': '#0F1C2E',
          info: '#378ADD',
          'info-content': '#ffffff',
          success: '#0F6E56',
          'success-content': '#ffffff',
          warning: '#BA7517',
          'warning-content': '#ffffff',
          error: '#A32D2D',
          'error-content': '#ffffff',
        },
      },
      {
        dark: {
          'color-scheme': 'dark',
          primary: '#378ADD',
          'primary-content': '#ffffff',
          secondary: '#85B7EB',
          'secondary-content': '#042C53',
          accent: '#1D9E75',
          'accent-content': '#ffffff',
          neutral: '#B5D4F4',
          'neutral-content': '#05111F',
          'base-100': '#0C1D2E',
          'base-200': '#071525',
          'base-300': '#1A3048',
          'base-content': '#D6E8F8',
          info: '#85B7EB',
          'info-content': '#042C53',
          success: '#1D9E75',
          'success-content': '#04342C',
          warning: '#EF9F27',
          'warning-content': '#412402',
          error: '#E24B4A',
          'error-content': '#501313',
        },
      },
    ],
    defaultTheme: 'dark',
    logs: false,
  },
}