/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {},
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        light: {
          'color-scheme': 'light',
          primary: '#185FA5',
          'primary-content': '#ffffff',
          secondary: '#378ADD',
          'secondary-content': '#ffffff',
          accent: '#1D9E75',
          'accent-content': '#ffffff',
          neutral: '#2C3E50',
          'neutral-content': '#ffffff',
          'base-100': '#ffffff',
          'base-200': '#F2F5F9',
          'base-300': '#D8E3EF',
          'base-content': '#0F1C2E',
          info: '#378ADD',
          'info-content': '#ffffff',
          success: '#0F6E56',
          'success-content': '#ffffff',
          warning: '#BA7517',
          'warning-content': '#ffffff',
          error: '#A32D2D',
          'error-content': '#ffffff',
        },
      },
      {
        dark: {
          'color-scheme': 'dark',
          primary: '#00D9FF',
          'primary-content': '#000814',
          secondary: '#00F7FF',
          'secondary-content': '#000814',
          accent: '#FF006E',
          'accent-content': '#ffffff',
          neutral: '#4A5568',
          'neutral-content': '#E0E8FF',
          'base-100': '#0A0E27',
          'base-200': '#0F1535',
          'base-300': '#1A1F4B',
          'base-content': '#E0E8FF',
          info: '#00D9FF',
          'info-content': '#000814',
          success: '#00FF88',
          'success-content': '#000814',
          warning: '#FFB500',
          'warning-content': '#000814',
          error: '#FF3E5F',
          'error-content': '#ffffff',
        },
      },
    ],
    defaultTheme: 'dark',
    logs: false,
  },
}